import helpers
import database as db

def iniciar():
    helpers.limpiar_pantalla()
    a = db.Punto(2, 3)
    b = db.Punto(5, 5)
    c = db.Punto(-3, -1)
    d = db.Punto(0, 0)
    print(a.cuadrante())
    print(c.cuadrante())
    print(d.cuadrante())
    print("")
    print(a.vector(b))
    print(b.vector(a))
    print("")
    print(a.distancia(b))
    print(b.distancia(a))
    print("")
    print(a.distancia(db.Punto()))
    print(b.distancia(db.Punto()))
    print(c.distancia(db.Punto()))
    print("")
    rect = db.Rectangulo(a, b)
    print(f"La base del rectangulo = {rect.base()}")
    print(f"La altura del rectangulo = {rect.altura()}")
    print(f"El area del rectangulo = {rect.area()}")